// Procedural Web Audio: wind, wing flaps, chimes, ambient Middle-Eastern pad music.
// If assets/music.mp3 / sfx exist (e.g. generated by ElevenLabs) they're used instead.
export class Audio {
  constructor() {
    this.ctx = null;
    this.muted = false;
    this.buffers = {};
  }

  start() {
    if (this.ctx) { this.ctx.resume(); return; }
    const ctx = this.ctx = new (window.AudioContext || window.webkitAudioContext)();
    this.master = ctx.createGain(); this.master.gain.value = 0.8;
    const comp = ctx.createDynamicsCompressor();
    this.master.connect(comp).connect(ctx.destination);
    // Shared reverb.
    this.reverb = ctx.createConvolver();
    this.reverb.buffer = this.impulse(2.8);
    this.revGain = ctx.createGain(); this.revGain.gain.value = 0.35;
    this.reverb.connect(this.revGain).connect(this.master);

    // Wind: looping noise through a moving bandpass.
    const noise = ctx.createBufferSource();
    noise.buffer = this.noiseBuffer(3); noise.loop = true;
    this.windFilter = ctx.createBiquadFilter(); this.windFilter.type = 'bandpass'; this.windFilter.Q.value = 0.7; this.windFilter.frequency.value = 500;
    this.windGain = ctx.createGain(); this.windGain.gain.value = 0;
    noise.connect(this.windFilter).connect(this.windGain).connect(this.master);
    noise.start();

    this.musicGain = ctx.createGain(); this.musicGain.gain.value = 0.0;
    this.musicGain.connect(this.master); this.musicGain.connect(this.reverb);
    this.musicGain.gain.linearRampToValueAtTime(0.32, ctx.currentTime + 4);
    this.tryExternalMusic().then(ok => { if (!ok) this.startMusic(); });
  }

  async tryExternalMusic() {
    const src = window.__MUSIC_DATA__ || 'assets/music.mp3';
    if (!window.__MUSIC_DATA__ && !location.protocol.startsWith('http')) return false;
    try {
      const res = await fetch(src);
      if (!res.ok) return false;
      const buf = await this.ctx.decodeAudioData(await res.arrayBuffer());
      const s = this.ctx.createBufferSource(); s.buffer = buf; s.loop = true;
      const g = this.ctx.createGain(); g.gain.value = 0.9;
      s.connect(g).connect(this.musicGain); s.start();
      return true;
    } catch { return false; }
  }

  noiseBuffer(sec) {
    const b = this.ctx.createBuffer(1, this.ctx.sampleRate * sec, this.ctx.sampleRate);
    const d = b.getChannelData(0);
    let last = 0;
    for (let i = 0; i < d.length; i++) { const w = Math.random() * 2 - 1; last = (last + 0.02 * w) / 1.02; d[i] = last * 3.5 + w * 0.05; }
    return b;
  }

  impulse(sec) {
    const len = this.ctx.sampleRate * sec;
    const b = this.ctx.createBuffer(2, len, this.ctx.sampleRate);
    for (let c = 0; c < 2; c++) {
      const d = b.getChannelData(c);
      for (let i = 0; i < len; i++) d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, 2.5);
    }
    return b;
  }

  // Hijaz-flavoured ambient: drone + slow pad chords + sparse plucked arpeggio (original composition).
  startMusic() {
    const ctx = this.ctx;
    const root = 146.83; // D3
    const scale = [0, 1, 4, 5, 7, 8, 10, 12]; // D Hijaz
    const f = (deg, oct = 0) => root * Math.pow(2, (scale[((deg % 7) + 7) % 7] + 12 * (Math.floor(deg / 7) + oct)) / 12);
    // Drone.
    for (const [freq, g] of [[root / 2, 0.14], [root * 0.75, 0.05]]) {
      const o = ctx.createOscillator(); o.type = 'sawtooth'; o.frequency.value = freq;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 380;
      const gg = ctx.createGain(); gg.gain.value = g;
      o.connect(lp).connect(gg).connect(this.musicGain); o.start();
    }
    const chords = [[0, 2, 4], [3, 5, 0], [-1, 1, 4], [0, 2, 4], [5, 0, 2], [3, 5, 0], [4, 6, 1], [0, 2, 4]];
    const arp = [0, 2, 4, 7, 4, 2, 5, 4, 2, 1, 0, 1];
    const beat = 0.5;
    let t0 = ctx.currentTime + 0.5, bar = 0;
    const schedule = () => {
      while (t0 < ctx.currentTime + 4) {
        const ch = chords[bar % chords.length];
        for (const d of ch) this.pad(f(d, 0), t0, beat * 8);
        for (let i = 0; i < 8; i++) {
          if (Math.random() < 0.3) continue;
          const deg = arp[(bar * 8 + i) % arp.length] + ch[0];
          this.pluck(f(deg, 1), t0 + i * beat, 0.12);
        }
        if (bar % 2 === 0) this.frameDrum(t0); this.frameDrum(t0 + beat * 3, 0.5); this.frameDrum(t0 + beat * 6, 0.7);
        t0 += beat * 8; bar++;
      }
      this.musicTimer = setTimeout(schedule, 1000);
    };
    schedule();
  }

  pad(freq, t, dur) {
    const ctx = this.ctx;
    const g = ctx.createGain(); g.gain.setValueAtTime(0, t);
    g.gain.linearRampToValueAtTime(0.045, t + dur * 0.35); g.gain.linearRampToValueAtTime(0, t + dur * 1.05);
    const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 1200;
    for (const det of [-7, 7]) {
      const o = ctx.createOscillator(); o.type = 'triangle'; o.frequency.value = freq; o.detune.value = det;
      o.connect(lp); o.start(t); o.stop(t + dur * 1.1);
    }
    lp.connect(g).connect(this.musicGain);
  }

  pluck(freq, t, vol) {
    const ctx = this.ctx;
    const o = ctx.createOscillator(); o.type = 'triangle'; o.frequency.value = freq;
    const o2 = ctx.createOscillator(); o2.type = 'sine'; o2.frequency.value = freq * 2.01;
    const g = ctx.createGain(); g.gain.setValueAtTime(vol, t); g.gain.exponentialRampToValueAtTime(0.001, t + 1.4);
    const g2 = ctx.createGain(); g2.gain.value = 0.3;
    o.connect(g); o2.connect(g2).connect(g); g.connect(this.musicGain);
    o.start(t); o2.start(t); o.stop(t + 1.5); o2.stop(t + 1.5);
  }

  frameDrum(t, v = 1) {
    const ctx = this.ctx;
    const o = ctx.createOscillator(); o.type = 'sine';
    o.frequency.setValueAtTime(110, t); o.frequency.exponentialRampToValueAtTime(55, t + 0.25);
    const g = ctx.createGain(); g.gain.setValueAtTime(0.22 * v, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.4);
    o.connect(g).connect(this.musicGain); o.start(t); o.stop(t + 0.45);
  }

  setWind(speed01, boosting) {
    if (!this.ctx) return;
    const t = this.ctx.currentTime;
    this.windGain.gain.setTargetAtTime(0.05 + speed01 * 0.25 + (boosting ? 0.12 : 0), t, 0.3);
    this.windFilter.frequency.setTargetAtTime(300 + speed01 * 1100, t, 0.3);
  }

  flap() {
    if (!this.ctx) return;
    const ctx = this.ctx, t = ctx.currentTime;
    for (let k = 0; k < 2; k++) {
      const s = ctx.createBufferSource(); s.buffer = this.flapBuf ||= this.noiseBuffer(0.3);
      const bp = ctx.createBiquadFilter(); bp.type = 'bandpass'; bp.frequency.value = 700 + k * 300; bp.Q.value = 1.2;
      const g = ctx.createGain(); const tt = t + k * 0.11;
      g.gain.setValueAtTime(0, tt); g.gain.linearRampToValueAtTime(0.5, tt + 0.03); g.gain.exponentialRampToValueAtTime(0.001, tt + 0.16);
      s.connect(bp).connect(g).connect(this.master); s.start(tt); s.stop(tt + 0.2);
    }
  }

  chime(pitch = 0) {
    if (!this.ctx) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const base = 880 * Math.pow(2, pitch / 12);
    [1, 1.5, 2, 3.01].forEach((m, i) => {
      const o = ctx.createOscillator(); o.type = 'sine'; o.frequency.value = base * m;
      const g = ctx.createGain(); const tt = t + i * 0.07;
      g.gain.setValueAtTime(0, tt); g.gain.linearRampToValueAtTime(0.18 / (i + 1), tt + 0.01); g.gain.exponentialRampToValueAtTime(0.001, tt + 1.6);
      o.connect(g); g.connect(this.master); g.connect(this.reverb);
      o.start(tt); o.stop(tt + 1.7);
    });
  }

  ring() {
    if (!this.ctx) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const o = ctx.createOscillator(); o.type = 'triangle';
    o.frequency.setValueAtTime(520, t); o.frequency.exponentialRampToValueAtTime(1040, t + 0.25);
    const g = ctx.createGain(); g.gain.setValueAtTime(0.2, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.5);
    o.connect(g); g.connect(this.master); g.connect(this.reverb); o.start(t); o.stop(t + 0.55);
  }

  bump() {
    if (!this.ctx) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const o = ctx.createOscillator(); o.type = 'sine';
    o.frequency.setValueAtTime(140, t); o.frequency.exponentialRampToValueAtTime(40, t + 0.3);
    const g = ctx.createGain(); g.gain.setValueAtTime(0.5, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.35);
    o.connect(g).connect(this.master); o.start(t); o.stop(t + 0.4);
  }

  fanfare() {
    if (!this.ctx) return;
    [0, 4, 7, 12, 16].forEach((p, i) => setTimeout(() => this.chime(p - 12), i * 140));
  }

  toggleMute() {
    this.muted = !this.muted;
    if (this.master) this.master.gain.setTargetAtTime(this.muted ? 0 : 0.8, this.ctx.currentTime, 0.05);
    return this.muted;
  }
}
